import 'hh_model.dart';

class HhMockData {
  static const List<Hermano> hermanos = [
    Hermano(
      legajo: '95.278',
      apellidos: 'ALDERETE',
      nombres: 'Rodrigo Jesus',
      grado: '3',
      cargo: 'Venerable Maestro',
      afiliacion: 'Simple',
      domicilio: 'Gral Paz 1071 4 c',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3814456709',
      email: 'roalderete@gmail.com',
    ),
    Hermano(
      legajo: '92.425',
      apellidos: 'GARCIA',
      nombres: 'Cesar Daniel',
      grado: '3',
      cargo: '1er Vigilante',
      afiliacion: 'Simple',
      domicilio: 'Santa Fe 2514',
      localidad: 'San Miguel de Tucuman',
      telefonos: '0381-423-0820, 0381-15-504-6745',
      email: 'cdgarcia84@gmail.com',
    ),
    Hermano(
      legajo: '98.407',
      apellidos: 'MONTI',
      nombres: 'Guillermo Ernesto',
      grado: '3',
      cargo: '2do Vigilante',
      afiliacion: 'Simple',
      domicilio: 'Madre de Luna 2026 11 A',
      localidad: 'San Miguel de Tucuman',
      telefonos: '0381-156823703',
      email: 'gmonti@lagaceta.com.ar',
    ),
    Hermano(
      legajo: '93.744',
      apellidos: 'LA MORGIA',
      nombres: 'Luis Federico',
      grado: '3',
      cargo: 'Orador',
      afiliacion: 'Simple',
      domicilio: 'Ayacucho 427 Planta Baja dpto B',
      localidad: 'Capital',
      telefonos: '4248-156, 0381-15-5179-821',
      email: 'flamorgia@gmail.com',
    ),
    Hermano(
      legajo: '92.911',
      apellidos: 'ARRIGHI',
      nombres: 'Carlos Federico',
      grado: '3',
      cargo: 'Secretario',
      afiliacion: 'Simple',
      domicilio: 'Miguel Lillo 1351',
      localidad: 'San Miguel de Tucuman',
      telefonos: '0381-4364-113, 0381-4883-272',
      email: 'tarturambar@gmail.com',
    ),
    Hermano(
      legajo: '17.238',
      apellidos: 'PONDAL',
      nombres: 'Carlos Martin',
      grado: '3',
      cargo: 'Tesorero',
      afiliacion: 'Simple',
      domicilio: 'San Juan 808 2 C',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3816808819',
      email: 'pondal@gmail.com',
    ),
    Hermano(
      legajo: '94.507',
      apellidos: 'ALCAIDE',
      nombres: 'Pablo Leonardo',
      grado: '3',
      cargo: 'Ninguno',
      afiliacion: 'Simple',
      domicilio: 'Pje Federico Brandsen 2870',
      localidad: 'San Miguel de Tucuman',
      telefonos: '0381-4322-160, 0381-15-4902-593',
      email: 'martilleroalcaide@gmail.com',
    ),
    Hermano(
      legajo: '108.629',
      apellidos: 'AMAYA',
      nombres: 'Sergio Gustavo',
      grado: '1',
      cargo: 'Ninguno',
      afiliacion: 'Simple',
      domicilio: 'San Juan 433 6to A',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3814686427',
      email: 'gustavo.amaya81@gmail.com',
    ),
    Hermano(
      legajo: '106.050',
      apellidos: 'GRANEROS',
      nombres: 'Martin Miguel',
      grado: '2',
      cargo: 'Ninguno',
      afiliacion: 'Simple',
      domicilio: 'Virgen de la Merced 639 Piso 4 Depto H',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3816213920',
      email: 'martinmgraneros@gmail.com',
    ),
    Hermano(
      legajo: '106.654',
      apellidos: 'SEMOLA',
      nombres: 'Guillermo Osvaldo',
      grado: '1',
      cargo: 'Ninguno',
      afiliacion: 'Simple',
      domicilio: 'Santa Fe 926 4to A',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3813578203',
      email: 'guillermosemola@hotmail.com',
    ),
    Hermano(
      legajo: '108.100',
      apellidos: 'ZANOTTA SARZUR',
      nombres: 'Stefano Martin',
      grado: '1',
      cargo: 'Ninguno',
      afiliacion: 'Simple',
      domicilio: 'Junin 785 4to A',
      localidad: 'San Miguel de Tucuman',
      telefonos: '3816558123',
      email: 'zanotta.stefano@gmail.com',
    ),
  ];
}
